name: CI Pipeline

# Тригер для запуску пайплайну на події push та pull_request до гілки main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Завантаження коду з репозиторію
    - name: Checkout repository
      uses: actions/checkout@v2

    # Встановлення Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Діагностичні кроки для перевірки поточної директорії та файлів
    - name: Show current directory
      run: pwd
    - name: List files
      run: ls -la

    # Встановлення залежностей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    # Запуск flake8 для перевірки стилю коду
    - name: Run linter
      run: flake8 .

    # Запуск тестів
    - name: Run tests
      run: python -m unittest discover -s CalculatorApp -p "test_*.py"
